### ISSUE TITLE
Problem Creating New Employee (Blazor Server-side)

### ISSUE THREAD

**Issue by aitlahmid** [DevExpress-Examples/XAF_how-to-use-the-integrated-mode-of-the-security-system-in-non-xaf-applications-e4908#38]
Hi
Thank you for your exemple

In Blazor application, i have a problem when clicking button 'New':

**System.MissingMethodException: Constructor on type 'XafSolution.Module.BusinessObjects.Employee' not found.
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at DevExpress.Blazor.Internal.Grid.DefaultDataGridEditingService`1.CreateSampleDataItem()
   at DevExpress.Blazor.Internal.Grid.DefaultDataGridEditingService`1.GetSampleItem()
   at DevExpress.Blazor.Internal.Grid.DefaultDataGridEditingService`1.AddNew()
   at DevExpress.Blazor.Base.DxDataGridBase`1.StartRowEdit(Object dataItem)
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)**

Thank you.

**Comment by AndreyKozhevnikov** [comment]
Hello,

Thank you for taking your time to test this example. Please give us additional time to research the behavior. We will update this thread once we have any news.

Andrey

**Comment by AndreyKozhevnikov** [comment]
Hello,

Thank you for your patience. We fixed the issue in the context of the following thread: [T857520 - DataGrid for Blazor - An edit form is not shown after the New button is clicked for the first time if the grid's model doesn't have a default constructor without parameters](https://supportcenter.devexpress.com/ticket/details/t857520/datagrid-for-blazor-an-edit-form-is-not-shown-after-the-new-button-is-clicked-for-the). Please await the next version of DevExpress Blazor UI Components.

Thanks,
Andrey
